# Generated by Django 5.0.7 on 2026-01-10 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('para', models.CharField(max_length=200)),
                ('cargo_para', models.CharField(max_length=200)),
                ('de', models.CharField(blank=True, max_length=200)),
                ('cargo_de', models.CharField(blank=True, max_length=200)),
                ('fecha_solicitud', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('partida_contable', models.CharField(max_length=200)),
                ('con_factura', models.CharField(max_length=50)),
                ('efectivo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.comparativequote')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.provider')),
            ],
        ),
    ]
