# Generated by Django 5.0.7 on 2026-01-14 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_provider_codigo'),
        ('payments', '0001_initial'),
        ('procurement', '0002_rename_motivo_comparativequote_motivo_seleccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='op_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='cuadro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='procurement.comparativequote'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='catalog.provider'),
        ),
        migrations.CreateModel(
            name='PaymentOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.paymentorder')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
    ]
