# Generated by Django 5.0.7 on 2026-01-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentorder_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='es_parcial',
            field=models.BooleanField(default=False, help_text='Marca si esta OP es un pago parcial (anticipo/saldo).'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='monto_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se llena, este será el monto a pagar (ej. anticipo). Si está vacío, se paga el total.', max_digits=12, null=True),
        ),
    ]
