# Generated by Django 5.0.7 on 2026-01-16 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentorder_es_parcial_paymentorder_monto_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='importe',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='op_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='cargo_para',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='con_factura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='efectivo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='es_parcial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='monto_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='para',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='partida_contable',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
