# Generated by Django 5.0.7 on 2026-01-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_paymentorder_importe_paymentorder_aprobado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='proyecto',
            field=models.CharField(blank=True, default='Uso Contable', max_length=200),
        ),
    ]
