# Generated by Django 5.0.7 on 2026-01-20 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentorder_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='pago_parcial_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complementos', to='payments.paymentorder'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='proyecto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
