# Generated by Django 5.0.7 on 2026-01-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('doc_type', 'year')},
            },
        ),
    ]
