# Generated by Django 5.0.7 on 2026-01-10 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('item_cotizado', models.CharField(max_length=200)),
                ('proyecto', models.CharField(max_length=200)),
                ('expresado_en', models.CharField(default='Bolivianos', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_creados', to=settings.AUTH_USER_MODEL)),
                ('proveedor_seleccionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ComparativePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.provider')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='procurement.comparativequote')),
            ],
            options={
                'unique_together': {('cuadro', 'proveedor', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ComparativeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(default='Und', max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.comparativequote')),
            ],
            options={
                'unique_together': {('cuadro', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ComparativeSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=250)),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='procurement.comparativequote')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.provider')),
            ],
            options={
                'unique_together': {('cuadro', 'proveedor')},
            },
        ),
    ]
