# Generated by Django 5.0.7 on 2026-01-11 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparativequote',
            old_name='motivo',
            new_name='motivo_seleccion',
        ),
        migrations.AlterField(
            model_name='comparativequote',
            name='proveedor_seleccionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seleccionado_en', to='procurement.comparativesupplier'),
        ),
    ]
