# Generated by Django 5.0.7 on 2026-01-23 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_comparativequote_revisado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativequote',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparativequote',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cc_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comparativequote',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20),
        ),
    ]
