# Generated by Django 5.0.7 on 2026-01-25 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_comparativequote_aprobado_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparativeQuoteAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo", models.FileField(upload_to="cc_cotizaciones/%Y/%m/%d/")),
                ("nombre", models.CharField(blank=True, max_length=255)),
                ("subido_en", models.DateTimeField(auto_now_add=True)),
                ("cuadro", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="adjuntos", to="procurement.comparativequote")),
                ("subido_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cc_adjuntos_subidos", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
