# Generated by Django 5.0.7 on 2026-01-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(default='Und', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('datos_transferencia', models.CharField(blank=True, max_length=250)),
                ('entidad', models.CharField(blank=True, max_length=100)),
                ('nro_cuenta', models.CharField(blank=True, max_length=50)),
                ('ci', models.CharField(blank=True, max_length=30)),
                ('nit', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
